version: "3.8"
services:
  # Database for storing user data
  postgres:
    container_name: postgres
    image: postgres:14.6
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social
    # volumes:
    #   - ./database/.data/postgres-data:/var/lib/postgresql/data

  # Database viewer/gui
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    user: root
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      

  ecs-container:
    container_name: ecs-container
    build:
      context: ./ecs
      dockerfile: dockerfile
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    environment:
      POSTGRES_READ_WRITE_ENDPOINT: postgres
      POSTGRES_READ_ENDPOINT: postgres
      POSTGRES_DB: social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"