version: '3'

tasks:
  build:
    desc: Build containers that use a dockerfile
    cmds:
      - docker compose build
  up:
    desc: Start docker compose containers
    cmds:
      - docker compose up -d {{.CLI_ARGS}}
  
  down:
    desc: Stop docker compose containers
    cmds:
      - docker compose down {{.CLI_ARGS}}

  logs:
    desc: Show all logs from docker compose containers
    cmds:
      - docker compose logs {{.CLI_ARGS}}

  tail:
    desc: Follow output from docker compose containers
    cmds:
      - docker compose logs --tail=0 --follow {{.CLI_ARGS}}

  term:
    desc: Opens a shell in container matching NAME.
    cmds:
      - docker exec -it {{.NAME}} /bin/sh

  ps:
    desc: Show running processes for docker compose
    cmds:
      - docker compose ps