FROM mcr.microsoft.com/devcontainers/go:0-1.19

# Install atlasGO
RUN curl -sSf https://atlasgo.sh | sh

# Install task
RUN go install github.com/go-task/task/v3/cmd/task@latest

# Install AWS SAM
RUN curl -LO https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip &&\
unzip aws-sam-cli-linux-x86_64.zip -d /sam-installation &&\
/sam-installation/install
